// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.2
// source: rates.proto

package rates_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RatesV1Client is the client API for RatesV1 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RatesV1Client interface {
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
}

type ratesV1Client struct {
	cc grpc.ClientConnInterface
}

func NewRatesV1Client(cc grpc.ClientConnInterface) RatesV1Client {
	return &ratesV1Client{cc}
}

func (c *ratesV1Client) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/rates_v1.RatesV1/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RatesV1Server is the server API for RatesV1 service.
// All implementations must embed UnimplementedRatesV1Server
// for forward compatibility
type RatesV1Server interface {
	Get(context.Context, *GetRequest) (*GetResponse, error)
	mustEmbedUnimplementedRatesV1Server()
}

// UnimplementedRatesV1Server must be embedded to have forward compatible implementations.
type UnimplementedRatesV1Server struct {
}

func (UnimplementedRatesV1Server) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedRatesV1Server) mustEmbedUnimplementedRatesV1Server() {}

// UnsafeRatesV1Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RatesV1Server will
// result in compilation errors.
type UnsafeRatesV1Server interface {
	mustEmbedUnimplementedRatesV1Server()
}

func RegisterRatesV1Server(s grpc.ServiceRegistrar, srv RatesV1Server) {
	s.RegisterService(&RatesV1_ServiceDesc, srv)
}

func _RatesV1_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RatesV1Server).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rates_v1.RatesV1/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RatesV1Server).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RatesV1_ServiceDesc is the grpc.ServiceDesc for RatesV1 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RatesV1_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rates_v1.RatesV1",
	HandlerType: (*RatesV1Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _RatesV1_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rates.proto",
}
